# Generated by Django 5.2.1 on 2026-07-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useractivity_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='accounts_us_created_f371fd_idx',
            old_name='accounts_us_created_0a2cab_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='accounts_us_user_id_506163_idx',
            old_name='accounts_us_user_id_1c6fa0_idx',
        ),
    ]
