# Generated by Django 5.2.1 on 2026-07-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_systemsetting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcementseen',
            new_name='accounts_an_announc_069374_idx',
            old_name='accounts_ann_announce_5fa283_idx',
        ),
        migrations.RenameIndex(
            model_name='announcementseen',
            new_name='accounts_an_announc_285fba_idx',
            old_name='accounts_ann_announce_62ef0a_idx',
        ),
    ]
