# Generated by Django 5.2.1 on 2026-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_allow_manual_certificate_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='allow_manual_certificate_no',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='allow_manual_sample_reg_no',
        ),
    ]
