# Generated by Django 5.2.1 on 2026-08-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_manual_numbering_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'permissions': [('manage_system_settings', 'Can manage system settings'), ('edit_tinymce_source', 'Can edit TinyMCE source code'), ('manage_users', 'Can create and manage limited users')]},
        ),
    ]
