# Generated by Django 5.2.1 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_delegated_user_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
