# Generated by Django 5.2.1 on 2026-05-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_customer_sr_no'),
        ('reports', '0008_report_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cs', 'CS'), ('ads', 'ADS'), ('ac', 'AC'), ('checklist', 'Checklist'), ('trf', 'TRF'), ('job_order', 'Print Job Order')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='tds_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(blank=True, help_text='Use this for ADS test-wise templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_document_templates', to='bookings.testmaster')),
            ],
            options={
                'ordering': ['document_type', 'test__name', 'name'],
                'unique_together': {('document_type', 'name', 'test')},
            },
        ),
    ]
