# Generated by Django 5.2.1 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_tdsdocumenttemplate_header_content_and_footer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='protect_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
