# Generated by Django 5.2.1 on 2026-06-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_protect_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='protect_pdf',
        ),
    ]
