# Generated by Django 5.2.1 on 2026-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_report_protect_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLetterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Letterhead', max_length=120)),
                ('layout_mode', models.CharField(choices=[('default', 'Use current default'), ('full', 'Full page image'), ('parts', 'Header / Middle / Footer')], default='default', max_length=20)),
                ('full_image', models.FileField(blank=True, null=True, upload_to='test_letterheads/')),
                ('header_image', models.FileField(blank=True, null=True, upload_to='test_letterheads/')),
                ('middle_image', models.FileField(blank=True, null=True, upload_to='test_letterheads/')),
                ('footer_image', models.FileField(blank=True, null=True, upload_to='test_letterheads/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Letterhead',
                'verbose_name_plural': 'Test Letterhead',
            },
        ),
    ]
