# Generated by Django 5.2.1 on 2026-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_activate_uploaded_full_letterheads'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaletterhead',
            name='report_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coaletterhead',
            name='show_report_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testletterhead',
            name='report_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testletterhead',
            name='show_report_title',
            field=models.BooleanField(default=True),
        ),
    ]
