# Generated by Django 5.2.1 on 2026-08-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_letterhead_report_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaletterhead',
            options={'permissions': [('manage_letterheads', 'Can upload and manage COA and Test letterheads')], 'verbose_name': 'COA Letterhead', 'verbose_name_plural': 'COA Letterhead'},
        ),
    ]
