# Generated by Django 5.2.1 on 2026-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_customer_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplenamemaster',
            name='customer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='discipline',
            field=models.CharField(blank=True, choices=[('NABL', 'NABL'), ('Pharma', 'Pharma')], max_length=40),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='limits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='observationsheet_prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('API', 'API'), ('FG', 'FG'), ('Food', 'Food'), ('RM', 'RM')], max_length=20),
        ),
        migrations.AddField(
            model_name='samplenamemaster',
            name='test_group',
            field=models.CharField(blank=True, choices=[('Biological Section', 'Biological Section'), ('Chemical/Instrument Section', 'Chemical/Instrument Section')], max_length=80),
        ),
    ]
