# Generated by Django 5.2.1 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_samplenamemaster_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
