# Generated by Django 5.2.1 on 2026-06-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_customermaster_pdf_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermaster',
            name='pdf_password',
        ),
    ]
