# Generated by Django 5.2.1 on 2026-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_billingrecord_bill_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='billing_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='letter_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
