# Generated by Django 5.2.1 on 2026-08-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_billingundorecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingundorecord',
            options={'ordering': ['-undone_at', '-pk'], 'verbose_name': 'Billing undo record', 'verbose_name_plural': 'Billing undo records'},
        ),
    ]
