# Generated by Django 5.2.1 on 2026-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_alter_billingundorecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_certificate_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sample_reg_no',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
