# Generated by Django 5.2.1 on 2026-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_manual_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'permissions': [('view_data_sheet', 'Can view Data Sheet'), ('assign_booking', 'Can assign bookings')]},
        ),
    ]
